/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoundIndexRouteImport } from './routes/sound/index'
import { Route as ColorIndexRouteImport } from './routes/color/index'
import { Route as SoundGameRouteImport } from './routes/sound/game'
import { Route as ColorGameRouteImport } from './routes/color/game'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundIndexRoute = SoundIndexRouteImport.update({
  id: '/sound/',
  path: '/sound/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorIndexRoute = ColorIndexRouteImport.update({
  id: '/color/',
  path: '/color/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundGameRoute = SoundGameRouteImport.update({
  id: '/sound/game',
  path: '/sound/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorGameRoute = ColorGameRouteImport.update({
  id: '/color/game',
  path: '/color/game',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/color/game': typeof ColorGameRoute
  '/sound/game': typeof SoundGameRoute
  '/color/': typeof ColorIndexRoute
  '/sound/': typeof SoundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/color/game': typeof ColorGameRoute
  '/sound/game': typeof SoundGameRoute
  '/color': typeof ColorIndexRoute
  '/sound': typeof SoundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/color/game': typeof ColorGameRoute
  '/sound/game': typeof SoundGameRoute
  '/color/': typeof ColorIndexRoute
  '/sound/': typeof SoundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/color/game' | '/sound/game' | '/color/' | '/sound/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/color/game' | '/sound/game' | '/color' | '/sound'
  id: '__root__' | '/' | '/color/game' | '/sound/game' | '/color/' | '/sound/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorGameRoute: typeof ColorGameRoute
  SoundGameRoute: typeof SoundGameRoute
  ColorIndexRoute: typeof ColorIndexRoute
  SoundIndexRoute: typeof SoundIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound/': {
      id: '/sound/'
      path: '/sound'
      fullPath: '/sound/'
      preLoaderRoute: typeof SoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color/': {
      id: '/color/'
      path: '/color'
      fullPath: '/color/'
      preLoaderRoute: typeof ColorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound/game': {
      id: '/sound/game'
      path: '/sound/game'
      fullPath: '/sound/game'
      preLoaderRoute: typeof SoundGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color/game': {
      id: '/color/game'
      path: '/color/game'
      fullPath: '/color/game'
      preLoaderRoute: typeof ColorGameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorGameRoute: ColorGameRoute,
  SoundGameRoute: SoundGameRoute,
  ColorIndexRoute: ColorIndexRoute,
  SoundIndexRoute: SoundIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
